name: "Factorio Mod Uploader"
description: "Upload a Factorio mod with preliminary checks"
author: "TheBrutalX"
branding:
  icon: "activity"
  color: "green"
inputs:
  action:
    description: "Action to perform"
    required: true
  mod-folder:
    description: "Path to the mod folder to upload"
    required: false
  mod-name:
    description: "Name of the mod to upload"
    required: false
  mod-version:
    description: "Version of the mod to upload"
    required: false
  factorio-api-key:
    description: "API token for authenticating with the Factorio store"
    required: false
  dotignore:
    description: "Path to the .ignore file to use"
    default: ".factorioignore"
    required: false
  zip-file:
    description: "Path to the zip file to upload"
    required: false
runs:
  using: "node20"
  main: "dist/bundle.js"
