name: "Factorio Mod Uploader"
description: "Upload a Factorio mod with preliminary checks"
author: "TheBrutalX"
branding:
  icon: "activity"
  color: "green"
inputs:
  action:
    description: "Action to perform"
    required: true
  mod-folder:
    description: "Path to the mod folder to upload"
    required: false
  factorio-token:
    description: "API token for authenticating with the Factorio store"
    required: false
runs:
  using: "node16"
  main: "dist/bundle.js"
