name: Update Latest Tag

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update latest tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git tag -d latest || true
          git push origin :refs/tags/latest || true
          
          # Create new latest tag
          git tag -fa latest
          git push origin latest --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}