name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
          - v1
          - v2

env:
  BOT_APPID: 1044190

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ env.BOT_APPID }}
        private-key: ${{ secrets.BOT_TOKEN }}

    - name: Git config
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Tag new target
      run: git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}

    - name: Push new tag
      run: git push origin ${{ github.event.inputs.major_version }} --force