name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
          - v1
          - v2
          - v3

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:

    - name: App Authentication
      uses: actions/create-github-app-token@v1
      id: auth
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_KEY }}
        repositories: ${{ github.event.repository.name }}
        owner: ${{ github.repository_owner }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.auth.outputs.token }}

    - name: Set up Git
      run: |
        git config user.name 'release[bot]'
        git config user.email '${{ steps.auth.outputs.app-slug }}@github.com'

    - name: Assing version to ${{ github.event.inputs.major_version }}
      run: |
        git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}
        git push -f origin ${{ github.event.inputs.major_version }}
